/**
 * What the builder's Code workshop needs to show a project's files: a folder
 * tree, a language per file and highlighted source.
 *
 * Pure string work, no DOM, so it is tested directly. Everything that reaches
 * HTML goes through `escapeHtml` here: the files are generated by a model and
 * may contain anything, `<script>` included.
 */

export type TreeFolder = { kind: 'folder'; name: string; path: string; children: TreeNode[] };
export type TreeFile = { kind: 'file'; name: string; path: string };
export type TreeNode = TreeFolder | TreeFile;

export function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

/** Folders first, then files, each alphabetical; `index.html` and package.json lead their folder. */
export function buildFileTree(paths: string[]): TreeNode[] {
  const root: TreeFolder = { kind: 'folder', name: '', path: '', children: [] };
  for (const raw of paths) {
    const parts = raw.split('/').filter(Boolean);
    let folder = root;
    parts.forEach((part, index) => {
      const path = parts.slice(0, index + 1).join('/');
      if (index === parts.length - 1) {
        folder.children.push({ kind: 'file', name: part, path: raw });
        return;
      }
      let next = folder.children.find((child): child is TreeFolder => child.kind === 'folder' && child.name === part);
      if (!next) {
        next = { kind: 'folder', name: part, path, children: [] };
        folder.children.push(next);
      }
      folder = next;
    });
  }
  const lead = (name: string) => (name === 'index.html' || name === 'package.json' ? 0 : 1);
  const sort = (nodes: TreeNode[]) => {
    nodes.sort((a, b) => {
      if (a.kind !== b.kind) return a.kind === 'folder' ? -1 : 1;
      return lead(a.name) - lead(b.name) || a.name.localeCompare(b.name, 'fr');
    });
    nodes.forEach(node => { if (node.kind === 'folder') sort(node.children); });
  };
  sort(root.children);
  return root.children;
}

export type Language = { id: 'js' | 'css' | 'html' | 'json' | 'md' | 'sql' | 'text'; label: string };

export function languageOf(path: string): Language {
  const extension = (path.split('.').pop() || '').toLowerCase();
  if (['ts', 'tsx'].includes(extension)) return { id: 'js', label: extension === 'tsx' ? 'TypeScript React' : 'TypeScript' };
  if (['js', 'jsx', 'mjs', 'cjs'].includes(extension)) return { id: 'js', label: extension === 'jsx' ? 'JavaScript React' : 'JavaScript' };
  if (['css', 'scss'].includes(extension)) return { id: 'css', label: 'CSS' };
  if (['html', 'htm', 'svg', 'xml', 'vue'].includes(extension)) return { id: 'html', label: extension === 'svg' ? 'SVG' : 'HTML' };
  if (extension === 'json') return { id: 'json', label: 'JSON' };
  if (['md', 'mdx'].includes(extension)) return { id: 'md', label: 'Markdown' };
  if (extension === 'sql') return { id: 'sql', label: 'SQL' };
  return { id: 'text', label: extension ? extension.toUpperCase() : 'Texte' };
}

type Token = { type: string; text: string };

const JS_KEYWORDS = new Set('abstract as async await break case catch class const continue default delete do else enum export extends false finally for from function get if implements import in instanceof interface let new null of private protected public readonly return set static super switch this throw true try type typeof undefined var void while yield'.split(' '));
const SQL_KEYWORDS = new Set('select from where insert into values update set delete create table alter drop index primary key foreign references not null default unique on and or join left right inner outer group by order limit offset as returning policy enable row level security using with check grant to function returns language begin end if exists'.split(' '));

/*
 * One scanning regex per language; each alternative is a named group so the
 * match says what it found. Anything unmatched is plain text.
 */
const PATTERNS: Record<Language['id'], RegExp | null> = {
  js: /(?<comment>\/\/[^\n]*|\/\*[\s\S]*?(?:\*\/|$))|(?<string>`(?:\\[\s\S]|[^\\`])*`?|"(?:\\.|[^\\"\n])*"?|'(?:\\.|[^\\'\n])*'?)|(?<tag><\/?[A-Za-z][\w.:-]*)|(?<number>\b\d[\d_]*(?:\.\d+)?(?:e[+-]?\d+)?\b)|(?<word>[A-Za-z_$][\w$]*)/g,
  css: /(?<comment>\/\*[\s\S]*?(?:\*\/|$))|(?<string>"(?:\\.|[^\\"\n])*"?|'(?:\\.|[^\\'\n])*'?)|(?<keyword>@[\w-]+|!important)|(?<prop>--?[A-Za-z][\w-]*(?=\s*:))|(?<number>#[0-9a-fA-F]{3,8}\b|-?\b\d+(?:\.\d+)?(?:px|rem|em|%|vh|vw|s|ms|deg|fr)?\b)/g,
  html: /(?<comment><!--[\s\S]*?(?:-->|$))|(?<tag><\/?[A-Za-z][\w:-]*|\/?>)|(?<attr>\b[A-Za-z_:][\w:.-]*(?==))|(?<string>"[^"\n]*"?|'[^'\n]*'?)/g,
  json: /(?<prop>"(?:\\.|[^\\"\n])*"(?=\s*:))|(?<string>"(?:\\.|[^\\"\n])*"?)|(?<number>-?\b\d+(?:\.\d+)?(?:e[+-]?\d+)?\b)|(?<keyword>\b(?:true|false|null)\b)/g,
  md: /(?<keyword>^#{1,6} [^\n]*)|(?<string>`[^`\n]*`)|(?<tag>\*\*[^*\n]+\*\*)/gm,
  sql: /(?<comment>--[^\n]*|\/\*[\s\S]*?(?:\*\/|$))|(?<string>'(?:''|[^'])*'?)|(?<number>\b\d+(?:\.\d+)?\b)|(?<word>[A-Za-z_][\w]*)/g,
  text: null,
};

function tokenize(source: string, language: Language['id']): Token[] {
  const pattern = PATTERNS[language];
  if (!pattern) return [{ type: '', text: source }];
  const tokens: Token[] = [];
  let last = 0;
  pattern.lastIndex = 0;
  for (let match = pattern.exec(source); match; match = pattern.exec(source)) {
    if (!match[0]) { pattern.lastIndex += 1; continue; }
    if (match.index > last) tokens.push({ type: '', text: source.slice(last, match.index) });
    const groups = match.groups || {};
    let type = Object.keys(groups).find(name => groups[name] !== undefined) || '';
    if (type === 'word') {
      const word = match[0];
      const next = source.slice(pattern.lastIndex).match(/^\s*\(/);
      if (language === 'sql') type = SQL_KEYWORDS.has(word.toLowerCase()) ? 'keyword' : '';
      else if (JS_KEYWORDS.has(word)) type = 'keyword';
      else if (next) type = 'call';
      // A capitalised name is a type where the syntax says so, not in JSX text ("Votre activité").
      else if (/^[A-Z]/.test(word) && (/(?:[:<|&]\s*|\b(?:new|extends|implements|as|type|interface|class)\s+)$/.test(source.slice(Math.max(0, match.index - 24), match.index)) || /^[.<]/.test(source.slice(pattern.lastIndex)))) type = 'type';
      else type = '';
    }
    tokens.push({ type, text: match[0] });
    last = pattern.lastIndex;
  }
  if (last < source.length) tokens.push({ type: '', text: source.slice(last) });
  return tokens;
}

/**
 * Highlighted HTML, one string per line, spans closed at each line end so a
 * line can be rendered on its own (a block comment spanning three lines
 * becomes three comment spans).
 */
export function highlightLines(source: string, language: Language['id']): string[] {
  const lines: string[] = [''];
  for (const token of tokenize(source.replace(/\r\n?/g, '\n'), language)) {
    token.text.split('\n').forEach((piece, index) => {
      if (index > 0) lines.push('');
      if (!piece) return;
      const html = escapeHtml(piece);
      lines[lines.length - 1] += token.type ? `<span class="syn-${token.type}">${html}</span>` : html;
    });
  }
  return lines;
}

/** A small coloured glyph per file type, drawn with currentColor. */
export function fileIconSvg(path: string): string {
  const extension = (path.split('.').pop() || '').toLowerCase();
  const tone = ['ts', 'tsx'].includes(extension) ? 'ts'
    : ['js', 'jsx', 'mjs', 'cjs'].includes(extension) ? 'js'
      : ['css', 'scss'].includes(extension) ? 'css'
        : ['html', 'htm', 'svg', 'xml'].includes(extension) ? 'html'
          : extension === 'json' ? 'json'
            : ['md', 'mdx'].includes(extension) ? 'md'
              : extension === 'sql' ? 'sql' : 'file';
  return `<svg class="code-file-icon" data-tone="${tone}" viewBox="0 0 24 24" aria-hidden="true"><path d="M14 3H7a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V8z"/><path d="M14 3v5h5"/></svg>`;
}

export const FOLDER_ICON_SVG = '<svg class="code-folder-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M3 7a2 2 0 0 1 2-2h4l2 2h8a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/></svg>';
export const CHEVRON_SVG = '<svg class="code-chevron" viewBox="0 0 24 24" aria-hidden="true"><path d="m9 6 6 6-6 6"/></svg>';
