import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { eligibleGrantRestrictions } from './src/services/credit-visibility.ts';
const server=readFileSync(new URL('./server.ts',import.meta.url),'utf8');
const fn=server.slice(server.indexOf('async function unifiedCategoryCredits('),server.indexOf('async function reserveUnifiedUsage('));
assert.match(fn,/\.eq\('account_id', accountId\)/);
assert.match(fn,/eligibleGrantRestrictions\(category\)/);
assert.deepEqual(eligibleGrantRestrictions('ai_gateway'),['ai_gateway','chat','agent','general']);
assert.deepEqual(eligibleGrantRestrictions('build'),['build','agent','general']);
assert.match(fn,/\.is\('frozen_at', null\)/);
assert.match(fn,/\.gt\('expires_at', new Date\(\)\.toISOString\(\)\)/);
assert.match(fn,/\.gt\('credits_remaining', 0\)/);
assert.match(fn,/throw new BillingLedgerUnavailableError\(\)/,'a database failure is not insufficient credit');
const chat=server.slice(server.indexOf("app.post('/api/assistant/chat'"),server.indexOf("app.get('/api/projects"));
assert.ok(chat.indexOf('await reserveUnifiedUsage(')<chat.indexOf('await createAgentTextResponse('),'reserve before paid response');
assert.ok(chat.indexOf('await completeDeliveredAction(')<chat.indexOf('await chargeCompletedAgentAction('),'atomic durable result before settlement');
assert.match(chat,/catch \(chargeError/,'accounting failure cannot destroy a delivered result');
assert.match(server,/checkpointDeliveredUsage/,'even failed usage-event inserts remain recoverable');
assert.match(server,/retryDeliveredSettlements/,'the background worker resumes settlement');
console.log('authoritative credit gate tests passed');
