import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { customerActionCredits } from './src/services/billing-action.ts';
const server=readFileSync(new URL('./server.ts',import.meta.url),'utf8');
assert.equal(customerActionCredits('conversation'),0.5);
assert.equal(customerActionCredits('full_page'),1.7);
assert.doesNotMatch(server,/autoCanHelp = (requested|effective)ModelSelection/,'model changes do not change the fixed action price');
assert.doesNotMatch(server,/publicCreditGateResponse\(frenchActivity, requestedModelSelection/);
assert.doesNotMatch(server,/selectedModel !== 'auto' && decision\.intent !== 'conversation',/);
assert.match(server,/diagnostic_code: 'CREDITS_REQUIRED'/);
assert.match(server,/BillingLedgerUnavailableError/);
assert.match(server,/Votre travail est conservé\. Rechargez votre solde pour reprendre/);
console.log('fixed-price credit gate advice tests passed');
