import assert from 'node:assert/strict';
import { readFileSync, existsSync } from 'node:fs';
const read = (path: string) => readFileSync(new URL(path, import.meta.url), 'utf8');
const html = read('./index.html');
const script = read('./src/landing-new.ts');
const mesh = read('./src/lib/brand-mesh.ts');
const css = read('./src/styles/landing-new.css');
const builder = read('./builder.html');
const live = read('./src/builder-live.ts');
const dashboard = read('./src/dashboard-react.tsx');
assert.equal((html.match(/<section /g) || []).length, 6, 'six primary sections only');
assert.equal((html.match(/<h1 /g) || []).length, 1);
assert.match(html, /Votre idée\.<br \/>Votre application\./);
for (const removed of ['Essayez :', '5 crédits offerts', 'Sans carte bancaire', 'Preview privée', 'Le plus choisi', 'Prête à publier']) {
  assert.ok(!html.toLowerCase().includes(removed.toLowerCase()), 'no unnecessary or unverified copy: ' + removed);
}
for (const id of ['landing-composer', 'landing-final-composer']) assert.equal((html.match(new RegExp('id="' + id + '"', 'g')) || []).length, 1);
assert.ok(html.indexOf('landing-final-composer') < html.indexOf('coden-marketing-footer-root'));
assert.match(script, /createLandingDraft\(storage\)/);
assert.match(script, /!draft.beginSubmit\(\)/);
assert.match(script, /model,\s*effort,/);
assert.match(script, /BILLING_PLANS\[plan\]\.tiers\[0\]/, 'minimum advertised price uses the real first tier');
assert.match(script, /priceFor\(plan, credits, interval\)/);
assert.ok(!html.includes('Quelques connecteurs du catalogue'));
assert.ok(!html.includes('lp-marquee-toggle'));
assert.match(html, /role="region" aria-label="Connecteurs disponibles\.[^"]*" aria-describedby="connector-note" tabindex="0"/);
assert.match(html, /id="connector-note">Disponibilité selon le connecteur et sa configuration\./);
assert.match(script, /clone\.setAttribute\('aria-hidden', 'true'\)/);
assert.match(script, /clone.inert = true/);
assert.doesNotMatch(script, /lp-marquee-toggle/);
assert.match(script, /String\(!onScreen \|\| document\.hidden \|\| motion\.matches\)/);
assert.match(css, /\.lp-marquee:hover \.lp-marquee-belt, \.lp-marquee:focus-within \.lp-marquee-belt/);
assert.match(css, /\.lp-product > \.lp-mesh\[data-lp-mesh="soft"\]\.is-ready/);
assert.match(css, /\.lp-marquee-track img[^}]*saturate\(\.5\)/);
assert.ok(!css.includes('lp-marquee-toggle'));
assert.match(css, /prefers-reduced-motion: reduce/);
assert.match(css, /html\[data-lp-reveal="on"\]/);
assert.ok(!script.includes('installScrollMotion'));
assert.match(script, /mountBrandMesh\(host, host.dataset.lpMesh/, 'the brand mesh is mounted behind landing sections');
assert.equal((html.match(/data-lp-mesh="/g) || []).length, 4, 'mesh behind hero, product, pricing and final sections');
assert.ok((html.match(/class="lp-mesh"[^>]*aria-hidden="true"/g) || []).length === 4, 'mesh is decorative only');
assert.match(mesh, /bindPointer\(host/, 'the mesh reacts to the pointer');
assert.match(mesh, /pointerdown/, 'a click sends a ripple');
assert.match(mesh, /if \(!reduced\) bindPointer/, 'no pointer motion with reduced motion');
const shell = read('./src/styles/public-shell.css');
assert.match(shell, /\.lp-mesh \{[^}]*pointer-events: none/, 'the shared mesh never catches the pointer');
const pageMotion = read('./src/lib/page-motion.ts');
const publicPage = read('./src/public-page.ts');
assert.match(publicPage, /mountHeroMesh/, 'every public page gets the same mesh as the landing');
assert.match(publicPage, /\.public-page-hero, \.pricing-page-hero/);
assert.match(pageMotion, /mountBrandMesh\(host, 'hero'\)/);
assert.match(html, /data-lp-tier="pro"/);
assert.match(html, /data-lp-tier="business"/);
assert.match(script, /enhanceSelect\(select/, 'the tier dropdown is the product menu');
assert.match(script, /BILLING_PLANS\[plan\]\.tiers\.map/, 'tiers come from the catalogue');
assert.match(css, /\.lp-hero h1, \.lp-hero-subtitle[^{]*\{ animation: lp-rise/, 'the first screen rises in');
for (const [, path] of html.matchAll(/src="(\/connector-logos\/[^"]+)"/g)) assert.ok(existsSync(new URL('./public' + path, import.meta.url)), 'local logo exists: ' + path);
assert.match(builder, /restrained --radius-md \(12px\) corners/);
assert.match(live, /if \(!cloudConsoleDatabase\) target.innerHTML = dbLoadingSkeleton/);
assert.match(live, /currentProjectId !== loadingProjectId/);
assert.match(dashboard, /projectsQuery.isError && !projectsQuery.data/);
assert.match(dashboard, /aria-busy=\{projectsQuery.isFetching\}/);
console.log('Minimal Landing, shared draft, marquee, pricing and loading contracts passed.');
