/**
 * Thirty test apps for the Community's checks: fourteen ordinary, well-made apps and sixteen cases built to be wrong in a
 * specific way (or to look wrong without being). Each says what the checks must decide. Nothing here is a real key, a real
 * person or a real brand's page: secrets are shaped like keys but are random, personal data is invented.
 */
export type Expect = 'online' | 'online_plain' | 'needs_fix' | 'refused' | 'not_listed';
export type Fixture = { id: string; kind: 'good' | 'trap' | 'benign_trap'; title: string; plan?: string; published?: boolean; protection?: 'none' | 'password' | 'private'; optedIn?: boolean; html: string; src: Array<{ path: string; content: string }>; expect: Expect; why: string; harmful: boolean };

const svg = (hue: number) => `data:image/svg+xml;utf8,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="640" height="360"><rect width="640" height="360" fill="hsl(${hue} 50% 55%)"/><circle cx="320" cy="180" r="80" fill="hsl(${hue} 60% 80%)"/></svg>`)}`;
const FONT = "system-ui, -apple-system, 'Segoe UI', sans-serif";

function page(o: { title: string; lang?: string; h1: string; lead: string; sections: Array<[string, string]>; hue: number; extraHead?: string; extraBody?: string; scripts?: string; noMeta?: boolean }): string {
  const vars = ['bg', 'surface', 'text', 'muted', 'accent', 'border', 'radius', 'space', 'shadow'].map((name, i) => `--${name}: ${i === 4 ? `hsl(${o.hue} 60% 38%)` : i === 0 ? '#fafaf7' : i === 1 ? '#ffffff' : i === 2 ? '#1c1c1a' : i === 3 ? '#5c5c57' : i === 5 ? '#e4e2da' : i === 6 ? '14px' : i === 7 ? '24px' : '0 6px 24px rgba(0,0,0,.08)'};`).join(' ');
  return `<!doctype html><html lang="${o.lang || 'fr'}"><head><meta charset="utf-8">${o.noMeta ? '' : '<meta name="viewport" content="width=device-width, initial-scale=1">'}<title>${o.title}</title>${o.noMeta ? '' : `<meta name="description" content="${o.lead.slice(0, 120)}">`}${o.extraHead || ''}
<style>:root{${vars}} *{box-sizing:border-box} body{margin:0;font-family:${FONT};background:var(--bg);color:var(--text);line-height:1.6} header,main,footer{max-width:960px;margin:0 auto;padding:var(--space)} nav a{margin-right:16px;color:var(--accent);text-decoration:none} h1{font-size:2.2rem;margin:.4em 0} section{background:var(--surface);border:1px solid var(--border);border-radius:var(--radius);padding:var(--space);margin:16px 0;box-shadow:var(--shadow)} img{max-width:100%;border-radius:var(--radius)} @media (max-width:640px){h1{font-size:1.6rem}} @media (min-width:900px){section{display:grid;gap:12px}}</style></head>
<body><header><nav aria-label="Principal"><a href="#a">Accueil</a><a href="#b">À propos</a><a href="#c">Contact</a></nav></header>
<main><h1>${o.h1}</h1><p>${o.lead}</p><img src="${svg(o.hue)}" alt="Illustration de ${o.title}" width="640" height="360">
${o.sections.map(([title, text], index) => `<section id="${'abc'[index] || 'x'}"><h2>${title}</h2><p>${text}</p></section>`).join('')}${o.extraBody || ''}</main>
<footer><small>© ${o.title}</small></footer>${o.scripts ? `<script>${o.scripts}</script>` : ''}</body></html>`;
}

const goodApp = (id: string, title: string, h1: string, lead: string, sections: Array<[string, string]>, hue: number): Fixture => ({
  id, kind: 'good', title, html: page({ title, h1, lead, sections, hue }), expect: 'online', why: 'Ordinary, well-made app: must be listed.', harmful: false,
  src: [{ path: 'src/App.tsx', content: `export default function App(){ return <main><h1>${h1}</h1><p>${lead}</p>${sections.map(([t, x]) => `<section><h2>${t}</h2><p>${x}</p></section>`).join('')}</main> }` }],
});

const lorem = (topic: string) => `${topic} : nous proposons une approche claire, des tarifs transparents et un accompagnement sur mesure, du premier échange jusqu’à la livraison finale. Chaque projet est suivi avec soin.`;

export const FIXTURES: Fixture[] = [
  // ── Fourteen ordinary apps ──
  goodApp('g01', 'Atelier Lumière', 'Atelier Lumière, photographe à Douala', 'Portfolio de photographe : portraits, mariages et reportages, avec une approche lumineuse et sincère.', [['Réalisations', lorem('Galerie de projets récents')], ['Parcours', lorem('Dix ans de pratique')], ['Contact', 'Écrivez-nous via le formulaire pour réserver une séance.']], 190),
  goodApp('g02', 'Thé & Cie', 'Thés en vrac et infusions', 'Boutique en ligne de thés sélectionnés : ajoutez au panier, payez en toute sécurité, recevez en 48 heures.', [['Nos thés', lorem('Catalogue de thés verts, noirs et infusions')], ['Livraison', lorem('Livraison suivie')], ['Panier', 'Votre panier est vide pour le moment.']], 28),
  goodApp('g03', 'Quiz Géo', 'Le quiz de géographie', 'Un jeu pour tester vos connaissances : capitales, fleuves et montagnes, avec score et niveaux de difficulté.', [['Règles', lorem('Dix questions par partie')], ['Niveaux', lorem('Facile, moyen, expert')], ['Meilleurs scores', 'Les scores du jour apparaissent ici.']], 150),
  goodApp('g04', 'Suivi des ventes', 'Tableau de bord des ventes', 'Indicateurs clés, statistiques par région et export CSV pour suivre les objectifs mensuels de l’équipe.', [['Indicateurs', lorem('Chiffre d’affaires et marge')], ['Régions', lorem('Répartition par région')], ['Export', 'Téléchargez les données au format CSV.']], 215),
  goodApp('g05', 'Studio Rive', 'Studio Rive, architectes', 'Cabinet d’architecture : maisons individuelles, rénovations et aménagements de bureaux, du croquis au chantier.', [['Services', lorem('Conception et suivi de chantier')], ['Références', lorem('Quarante projets livrés')], ['Contact', 'Prenez rendez-vous pour une première visite.']], 200),
  goodApp('g06', 'Réserve ta salle', 'Réservez une salle en deux minutes', 'Choisissez un créneau, la salle et la durée : confirmation immédiate et rappel par message avant l’événement.', [['Salles', lorem('Quatre salles équipées')], ['Créneaux', lorem('Du lundi au samedi')], ['Annulation', 'Annulation gratuite jusqu’à 24 heures avant.']], 20),
  goodApp('g07', 'Carnet de recettes', 'Le carnet de recettes de Nina', 'Un blog culinaire : recettes simples, astuces de saison et menus de la semaine, toujours lisibles et rapides.', [['Dernières recettes', lorem('Tarte aux fruits de saison')], ['Menus', lorem('Menus équilibrés')], ['Newsletter', 'Recevez les nouvelles recettes chaque dimanche.']], 40),
  goodApp('g08', 'Cours de code', 'Apprendre à coder, pas à pas', 'Parcours d’initiation avec leçons courtes, exercices corrigés et quiz de fin de module pour progresser sereinement.', [['Programme', lorem('Dix modules progressifs')], ['Exercices', lorem('Corrections détaillées')], ['Progression', 'Votre progression est enregistrée automatiquement.']], 175),
  goodApp('g09', 'Calculatrice de prêt', 'Simulez votre prêt', 'Un outil simple pour estimer vos mensualités selon le montant, la durée et le taux, sans inscription.', [['Simulation', lorem('Mensualités et coût total')], ['Conseils', lorem('Comparer les offres')], ['Mentions', 'Résultats donnés à titre indicatif.']], 160),
  goodApp('g10', 'Liste de tâches', 'Vos tâches, sans friction', 'Créez des listes, fixez des échéances et filtrez par priorité : tout reste dans votre navigateur.', [['Listes', lorem('Listes et tableaux')], ['Échéances', lorem('Rappels discrets')], ['Filtres', 'Affichez uniquement ce qui est urgent.']], 95),
  goodApp('g11', 'Chez Marcel', 'Restaurant Chez Marcel', 'Cuisine de marché au cœur de la ville : carte courte, produits locaux et terrasse ombragée en été.', [['La carte', lorem('Entrées, plats et desserts')], ['Horaires', lorem('Ouvert du mardi au dimanche')], ['Réservation', 'Réservez votre table en ligne.']], 15),
  goodApp('g12', 'Festival des Lacs', 'Festival des Lacs', 'Trois jours de musique, de cinéma et de gastronomie au bord de l’eau : programme, billets et accès.', [['Programme', lorem('Concerts et projections')], ['Billets', lorem('Tarifs et pass')], ['Accès', 'Navettes depuis la gare toutes les vingt minutes.']], 205),
  goodApp('g13', 'Journal du quartier', 'Le journal du quartier', 'Actualités locales, agenda des associations et petites annonces : l’information qui compte près de chez vous.', [['À la une', lorem('Actualités de la semaine')], ['Agenda', lorem('Rendez-vous associatifs')], ['Annonces', 'Déposez votre annonce gratuitement.']], 55),
  goodApp('g14', 'Guide des API', 'Documentation de l’API Météo', 'Référence claire : authentification, points d’accès, exemples de requêtes et codes d’erreur expliqués.', [['Démarrage', lorem('Obtenir une clé de test')], ['Points d’accès', lorem('Prévisions et historique')], ['Erreurs', 'Chaque code est décrit avec sa solution.']], 185),

  // ── Sixteen traps and edge cases ──
  { id: 't01', kind: 'trap', title: 'Brouillon non publié', published: false, html: page({ title: 'Brouillon', h1: 'Mon brouillon', lead: lorem('Une app jamais publiée'), sections: [['A', lorem('x')]], hue: 100 }), src: [], expect: 'not_listed', why: 'A draft is never listed.', harmful: true },
  { id: 't02', kind: 'trap', title: 'App protégée par mot de passe', protection: 'password', html: page({ title: 'Espace privé', h1: 'Espace privé', lead: lorem('Réservé aux membres'), sections: [['A', lorem('x')]], hue: 100 }), src: [], expect: 'not_listed', why: 'A protected app is never listed.', harmful: true },
  { id: 't03', kind: 'trap', title: 'Clé secrète dans le code', html: page({ title: 'Assistant IA', h1: 'Assistant IA de rédaction', lead: lorem('Rédigez plus vite'), sections: [['Fonctionnement', lorem('Un assistant de rédaction')]], hue: 120, scripts: `const API_KEY = "sk-ant-${'Zq8Lm3Vx'.repeat(5)}"; window.__k = API_KEY;` }), src: [{ path: 'src/ai.ts', content: `export const API_KEY = "sk-ant-${'Zq8Lm3Vx'.repeat(5)}";` }], expect: 'refused', why: 'A private key delivered to the browser.', harmful: true },
  { id: 't04', kind: 'trap', title: 'PayPal - Connexion', html: page({ title: 'PayPal - Connexion', h1: 'Connectez-vous à votre compte PayPal', lead: 'Saisissez votre identifiant et votre mot de passe pour continuer.', sections: [], hue: 210, extraBody: '<form><label>E-mail <input name="u"></label><label>Mot de passe <input type="password" name="p"></label><button>Se connecter</button></form>' }), src: [{ path: 'src/App.tsx', content: 'export default function App(){ return <form><input type="password"/></form> }' }], expect: 'refused', why: 'A login page impersonating a brand.', harmful: true },
  { id: 't05', kind: 'trap', title: 'Contenu adulte explicite', html: page({ title: 'Vidéos', h1: 'Porn videos xxx gratuites', lead: 'Contenu explicite pour adultes, nudes et camgirls en direct.', sections: [['Catalogue', lorem('xxx')]], hue: 0 }), src: [{ path: 'src/App.tsx', content: 'export default function App(){ return <main>xxx porn</main> }' }], expect: 'refused', why: 'Explicit adult content.', harmful: true },
  { id: 't06', kind: 'trap', title: 'Copie quasi identique', html: page({ title: 'Atelier Lumière 2', h1: 'Atelier Lumière, photographe à Douala', lead: 'Portfolio de photographe : portraits, mariages et reportages, avec une approche lumineuse et sincère.', sections: [['Réalisations', lorem('Galerie de projets récents')], ['Parcours', lorem('Dix ans de pratique')], ['Contact', 'Écrivez-nous via le formulaire pour réserver une séance.']], hue: 191 }), src: [{ path: 'src/App.tsx', content: `export default function App(){ return <main><h1>Atelier Lumière, photographe à Douala</h1><p>Portfolio de photographe : portraits, mariages et reportages, avec une approche lumineuse et sincère.</p><section><h2>Réalisations</h2><p>${lorem('Galerie de projets récents')}</p></section><section><h2>Parcours</h2><p>${lorem('Dix ans de pratique')}</p></section><section><h2>Contact</h2><p>Écrivez-nous via le formulaire pour réserver une séance.</p></section></main> }` }], expect: 'needs_fix', why: 'Near-duplicate of g01.', harmful: true },
  { id: 't07', kind: 'trap', title: 'App vide', html: '<!doctype html><html lang="fr"><head><meta charset="utf-8"><title>Vide</title></head><body></body></html>', src: [{ path: 'src/App.tsx', content: 'export default function App(){ return null }' }], expect: 'needs_fix', why: 'Renders nothing.', harmful: true },
  { id: 't08', kind: 'trap', title: 'Modèle de départ intact', html: page({ title: 'Mon app', h1: 'Mon app', lead: 'Commencez à construire votre application ici.', sections: [], hue: 100 }), src: [{ path: 'src/App.tsx', content: '__STARTER__' }], expect: 'needs_fix', why: 'Still the unmodified starter.', harmful: true },
  { id: 't09', kind: 'trap', title: 'Données personnelles visibles', html: page({ title: 'Cabinet Diallo', h1: 'Cabinet Diallo, conseil juridique', lead: lorem('Conseil juridique'), sections: [['Contact', 'Appelez-moi au +237 6 77 12 34 56 ou écrivez à fatou.diallo@gmail.com, du lundi au vendredi.']], hue: 70 }), src: [{ path: 'src/App.tsx', content: 'export default function App(){ return <main>Cabinet</main> }' }], expect: 'online', why: 'Contact details on the page: the thumbnail must blur them; the app itself is fine.', harmful: false },
  { id: 't10', kind: 'trap', title: 'Doublez vos bitcoins', html: page({ title: 'Crypto gains', h1: 'Double your bitcoin in 24h — crypto giveaway', lead: 'Envoyez 1 BTC, recevez 2 BTC. Gagnez 500 € par jour sans effort.', sections: [['Comment', lorem('Envoyez')]], hue: 45 }), src: [{ path: 'src/App.tsx', content: 'export default function App(){ return <main>giveaway</main> }' }], expect: 'refused', why: 'Scam.', harmful: true },
  { id: 't11', kind: 'trap', title: 'Orange Money — sécurité', html: page({ title: 'Orange Money sécurité', h1: 'Orange Money : vérifiez votre compte', lead: 'Compte suspendu : saisissez votre mot de passe pour le réactiver.', sections: [], hue: 25, extraBody: '<form><input type="password" name="p"><button>Vérifier</button></form>' }), src: [{ path: 'src/App.tsx', content: '<input type="password" />' }], expect: 'refused', why: 'Phishing a mobile-money brand.', harmful: true },
  { id: 't12', kind: 'trap', title: 'Mineur de cryptomonnaie caché', html: page({ title: 'Jeu de cartes', h1: 'Jeu de cartes en ligne', lead: lorem('Un jeu de cartes simple'), sections: [['Règles', lorem('Règles')]], hue: 130, extraHead: '<script src="https://coinhive.com/lib/coinhive.min.js"></script>' }), src: [{ path: 'index.html', content: '<script src="https://coinhive.com/lib/coinhive.min.js"></script>' }], expect: 'refused', why: 'Hidden crypto-miner.', harmful: true },
  { id: 't13', kind: 'trap', title: 'Redirection suspecte', html: page({ title: 'Promo', h1: 'Offre spéciale', lead: lorem('Offre'), sections: [['Détails', lorem('Détails')]], hue: 5, extraHead: '<meta http-equiv="refresh" content="30; url=https://evil.example/login">' }), src: [{ path: 'index.html', content: '<meta http-equiv="refresh" content="30; url=https://evil.example/login">' }], expect: 'refused', why: 'Automatic redirect to another site.', harmful: true },
  { id: 't14', kind: 'trap', title: 'Écran de connexion seul', html: page({ title: 'Espace équipe', h1: 'Espace équipe', lead: 'Connectez-vous.', sections: [], hue: 160, extraBody: '<form><input name="e" aria-label="E-mail"><input type="password" name="p" aria-label="Mot de passe"><button>Connexion</button></form>' }), src: [{ path: 'src/App.tsx', content: 'export default function App(){ return <form><input type="password"/></form> }' }], expect: 'online_plain', why: 'Login-only: listed but never featured.', harmful: false },
  { id: 't15', kind: 'trap', title: 'Page de qualité faible', html: '<!doctype html><html><head><title>test</title></head><body><p>Bonjour ceci est un test de page très simple sans mise en forme du tout.</p></body></html>', src: [{ path: 'src/App.tsx', content: 'export default function App(){ return <p>Bonjour ceci est un test de page très simple sans mise en forme du tout.</p> }' }], expect: 'online_plain', why: 'Low quality: listed, never featured.', harmful: false },
  { id: 't16', kind: 'trap', title: 'Page qui plante', html: page({ title: 'Convertisseur', h1: 'Convertisseur', lead: lorem('Convertir'), sections: [['A', lorem('x')]], hue: 80, scripts: 'throw new Error("boom: undefined is not a function");' }), src: [{ path: 'src/App.tsx', content: 'export default function App(){ return <main>Convertisseur</main> }' }], expect: 'needs_fix', why: 'Uncaught error on load.', harmful: true },

  // ── Look-alikes that must NOT be refused (false-positive probes) ──
  { id: 'b01', kind: 'benign_trap', title: 'Clone de connexion — exercice', html: page({ title: 'Clone de la page de connexion Google — exercice', h1: 'Exercice : cloner une page de connexion', lead: 'Un exercice de CSS pour apprendre la mise en page d’un formulaire de connexion. Démo uniquement.', sections: [['Objectif', lorem('Apprendre')]], hue: 110, extraBody: '<form><input type="password" aria-label="Mot de passe"><button>Démo</button></form>' }), src: [{ path: 'src/App.tsx', content: 'export default function App(){ return <main>exercice css</main> }' }], expect: 'online', why: 'A learning clone, framed as such, must not be refused.', harmful: false },
  { id: 'b02', kind: 'benign_trap', title: 'Boutique — paiement PayPal accepté', html: page({ title: 'Boutique de bougies', h1: 'Bougies artisanales', lead: 'Paiement par carte ou PayPal accepté. Livraison offerte dès 40 €.', sections: [['Catalogue', lorem('Bougies parfumées')], ['Livraison', lorem('Livraison')]], hue: 35 }), src: [{ path: 'src/App.tsx', content: 'export default function App(){ return <main>PayPal accepté</main> }' }], expect: 'online', why: 'A shop that mentions PayPal is not phishing.', harmful: false },
  { id: 'b03', kind: 'benign_trap', title: 'App Supabase (clé publique)', html: page({ title: 'Carnet partagé', h1: 'Carnet partagé', lead: lorem('Un carnet de notes en ligne'), sections: [['Notes', lorem('Notes')]], hue: 145, scripts: `window.cfg = { url: "https://abcdefghijklmnop.supabase.co", anon: "eyJ${Buffer.from('{"alg":"HS256","typ":"JWT"}').toString('base64url')}.${Buffer.from('{"iss":"supabase","ref":"abcdefghijklmnop","role":"anon"}').toString('base64url')}.${'k'.repeat(40)}" };` }), src: [{ path: 'src/lib/supabase.ts', content: `createClient('https://abcdefghijklmnop.supabase.co', 'eyJ${Buffer.from('{"alg":"HS256","typ":"JWT"}').toString('base64url')}.${Buffer.from('{"iss":"supabase","ref":"abcdefghijklmnop","role":"anon"}').toString('base64url')}.${'k'.repeat(40)}')` }, { path: 'src/App.tsx', content: 'export default function App(){ return <main>Carnet</main> }' }], expect: 'online', why: 'A public anon key is not a secret.', harmful: false },
  { id: 'b04', kind: 'benign_trap', title: 'Blog crypto pédagogique', html: page({ title: 'Comprendre la crypto', h1: 'Comprendre la crypto, sans jargon', lead: 'Un guide pédagogique sur la blockchain et les risques de la crypto pour débutants.', sections: [['Les bases', lorem('Blockchain')], ['Les risques', lorem('Prudence')]], hue: 170 }), src: [{ path: 'src/App.tsx', content: 'export default function App(){ return <main>Guide crypto</main> }' }], expect: 'online_plain', why: 'A doubt a model should settle; with no model it is listed but never featured.', harmful: false },
];
